# Generated by Django 4.2.23 on 2025-07-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название решения/постановления')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-псевдоним')),
                ('decision_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер документа')),
                ('decision_date', models.DateField(verbose_name='Дата принятия')),
                ('decision_type', models.CharField(choices=[('resolution', 'Постановление'), ('order', 'Распоряжение'), ('other', 'Прочее')], default='resolution', max_length=20, verbose_name='Тип документа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое содержание')),
                ('file', models.FileField(upload_to='council/decisions/files/', verbose_name='Файл документа')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Решение Кенеша',
                'verbose_name_plural': 'Решения Кенеша',
                'ordering': ['-decision_date', 'decision_number'],
            },
        ),
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО депутата')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='council/deputy_photos/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Краткая биография')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Контактный телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('constituency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Избирательный округ')),
                ('position_in_council', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность в кенеше')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный депутат')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Депутат',
                'verbose_name_plural': 'Депутаты',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
