# Generated by Django 4.2.23 on 2025-07-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-псевдоним')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория галереи',
                'verbose_name_plural': 'Категории галереи',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-псевдоним')),
                ('type', models.CharField(choices=[('image', 'Фотография'), ('video', 'Видео')], default='image', max_length=10, verbose_name='Тип')),
                ('file', models.FileField(upload_to='gallery/files/', verbose_name='Файл (фото/видео)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallerycategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Элемент галереи',
                'verbose_name_plural': 'Элементы галереи',
                'ordering': ['-published_date'],
            },
        ),
    ]
