# Generated by Django 4.2.23 on 2025-07-14 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название бюджета (например, Бюджет на 2025 год)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-псевдоним')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('file', models.FileField(upload_to='about/budget_files/', verbose_name='Файл бюджета')),
                ('budget_year', models.PositiveIntegerField(unique=True, verbose_name='Год бюджета')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации на сайте')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Бюджет для граждан',
                'verbose_name_plural': 'Бюджеты для граждан',
                'ordering': ['-budget_year'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-псевдоним')),
                ('content', models.TextField(verbose_name='Содержание страницы')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Информационная страница',
                'verbose_name_plural': 'Информационные страницы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/person_photos/', verbose_name='Фото')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Биография / Описание')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('reception_schedule', models.TextField(blank=True, null=True, verbose_name='График приема')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_leader', models.BooleanField(default=False, verbose_name='Руководитель (для главной страницы)')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Руководство и сотрудники',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название отчета')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-псевдоним')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('file', models.FileField(upload_to='about/reports/files/', verbose_name='Файл отчета')),
                ('report_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год отчета')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации на сайте')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-report_year', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отдела')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание деятельности')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон отдела')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email отдела')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='about.person', verbose_name='Руководитель отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['order', 'name'],
            },
        ),
    ]
