# Generated by Django 4.2.23 on 2025-07-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок объявления')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-псевдоним')),
                ('content', models.TextField(verbose_name='Содержание объявления')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Имя для связи')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон для связи')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для связи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/ads_images/', verbose_name='Изображение')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('pending', 'Ожидает модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('expired', 'Истек срок')], default='pending', max_length=20, verbose_name='Статус')),
                ('moderator_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий модератора')),
            ],
            options={
                'verbose_name': 'Объявление жителя',
                'verbose_name_plural': 'Объявления жителей',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок публикации')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-псевдоним')),
                ('content', models.TextField(verbose_name='Содержание публикации')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('author_contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email автора')),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/blog_images/', verbose_name='Изображение')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('pending', 'Ожидает модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('moderator_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий модератора')),
            ],
            options={
                'verbose_name': 'Публикация жителя',
                'verbose_name_plural': 'Блоги жителей',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
