# Generated by Django 4.2.23 on 2025-07-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-псевдоним')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('file', models.FileField(upload_to='documents/files/', verbose_name='Файл документа')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-published_date'],
            },
        ),
    ]
