# Generated by Django 5.2.4 on 2025-07-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО заявителя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email заявителя')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон заявителя')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема обращения')),
                ('message', models.TextField(verbose_name='Содержание обращения')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='appeals/attachments/', verbose_name='Прикрепленный файл')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время подачи')),
                ('status', models.CharField(choices=[('received', 'Получено'), ('in_progress', 'В работе'), ('resolved', 'Решено'), ('rejected', 'Отклонено')], default='received', max_length=20, verbose_name='Статус')),
                ('resolution_text', models.TextField(blank=True, null=True, verbose_name='Решение/Комментарий администрации')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
