# Generated by Django 4.2.23 on 2025-07-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-псевдоним')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('budget_needed', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Необходимый бюджет (KGS)')),
                ('expected_return', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ожидаемая доходность')),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='Контактное лицо')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для связи')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон для связи')),
                ('status', models.CharField(choices=[('idea', 'Идея'), ('planning', 'Планирование'), ('active', 'Активный'), ('completed', 'Завершен'), ('on_hold', 'Приостановлен')], default='idea', max_length=20, verbose_name='Статус проекта')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='investors/project_images/', verbose_name='Изображение проекта')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Инвестиционный проект',
                'verbose_name_plural': 'Инвестиционные проекты',
                'ordering': ['status', '-published_at'],
            },
        ),
    ]
