# Generated by Django 4.2.23 on 2025-07-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200, verbose_name='Организация (например, Скорая помощь)')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Важный телефон',
                'verbose_name_plural': 'Важные телефоны',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название достопримечательности')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-псевдоним')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='info/landmarks/', verbose_name='Изображение')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Расположение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Достопримечательность',
                'verbose_name_plural': 'Достопримечательности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaticInfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-псевдоним')),
                ('content', models.TextField(verbose_name='Содержание страницы')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Информационная страница',
                'verbose_name_plural': 'Информационные страницы (Справочная информация)',
            },
        ),
    ]
